.\" Copyright (C) astral
.\" See COPYING for details.

.TH CAT 1

.SH NAME
cat \- concatenate and print files

.SH SYNOPSIS
.B cat
[\fIoption\fR]... [\fIfile\fR]...

.SH DESCRIPTION
.B cat
concatenates and prints specified \fIfile\fR(s), or standard input if no
\fIfile\fR is specified.

.SS OPTIONS

.TP
.B -u
Write to standard output as bytes are being read.
