.\" Copyright (C) astral
.\" See COPYING for details.

.TH CAT 1

.SH NAME
cat \- concatenate files and print on the standard output

.SH SYNOPSIS
.B cat
[\fIoption\fR]... [\fIfile\fR]...

.SH DESCRIPTION
.B cat
will print the contents of stdin or the specified \fIfile\fR(s) to stdout.

If no option is specified, \fBcat\fR will buffer the output.

.SS OPTIONS

.TP
.B \-u
Print bytes as they are read without buffering.

.SH EXAMPLES

.nf
.B cat files
% file1.txt
Hello, world!
% file2.txt (empty)
% file3.txt
こんにちは、世界！

$ cat file1.txt file2.txt file3.txt
Hello, world!
こんにちは、世界！

.B bytes from stdin
$ cat -u
Hello, world!
Hello, world!

.B here documents
$ cat > foo.txt << _EOF
> Hello, world!
> こんにちは、世界！
> _EOF
$ cat foo.txt
Hello, world!
こんにちは、世界！
.fi
