.\" Copyright (C) astral
.\" See COPYING for details.

.TH CKSUM 1

.SH NAME
cksum \- print checksum and bytes of a file

.SH SYNOPSIS
.B cksum
[\fIfile\fR]...

.SH DESCRIPTION
.B cksum
prints CRC-32 checksum of octets in a file. If no \fIfile\fR is given, standard
input is used.

.SH SEE ALSO
.BR wc (1)
