.\" Copyright (C) astral
.\" See COPYING for details.

.TH ECHO 1

.SH NAME
echo \- print a string

.SH SYNOPSIS
.B echo
[\fIstring\fR]

.SH DESCRIPTION
.B echo
will print the \fIstring\fR to the standard output followed by a newline.

.SH EXAMPLES

.nf
.B No arguments
$ echo
<newline>

.B With arguments
$ echo "Hello, world!"
Hello, world!
.fi

.SH SEE ALSO
.BR printf (1)
