.\" Copyright (C) astral
.\" See COPYING for details.

.TH LS 1

.SH LS
ls \- list directory contents

.SH SYNOPSIS
.B ls
[\fIoption\fR]... [\fIfile\fR]...

.SH DESCRIPTION
.B ls
lists information about files in specified directories. If no \fIfile\fR is
specified, the current directory is used.

.SS OPTIONS

.TP
.B -a
Do not ignore entries starting with .

.TP
.B -A
Equivalent to -a, but ignore . and ..
